### ISSUE TITLE
Remember previously entered transaction names. 

### ISSUE THREAD

**Issue by unoukujou** [jameskokoska/Allowance#10]
On a monthly basis we're mostly creating the same transactions over and over. It would be useful to not have to type the transaction name every time.

Maybe have a way to easily re-use transaction names that we've used in the past, or just as we're typing the transaction name it can recommend autofill suggestions of previously used transaction names.

**Comment by jameskokoska** [comment]
Unfortunately I don't see these features being implemented.

My new project, Cashew has all these features: https://github.com/jameskokoska/Cashew
Feed free to check that one out!

Allowance is an intended limited application for design and ease of use. Allowance is also currently not maintained.
