### ISSUE TITLE
Theme doesn't change in Pop-ups

### ISSUE THREAD

**Issue by DAJ8112** [jameskokoska/Allowance#3]
I feel like the pop up should be changed according to the system theme .
It is always black and doesn't match the theme.

![light (2)](https://github.com/jameskokoska/Allowance/assets/73093934/2a8c50c6-a007-4ea5-aec4-19b6025a2b34)     ![dark (2)](https://github.com/jameskokoska/Allowance/assets/73093934/d5df5f1b-2241-4e8b-929e-98c7e3668550)

**Comment by jameskokoska** [comment]
Thanks for posting this issue! How are you getting the popups? It doesn't seem like it's from the app Allowance.

![Screenshot_20230820_134729.png](https://github.com/jameskokoska/Allowance/assets/50821962/8cdb310a-cf34-458a-85d7-52dc36b124f7)

![Screenshot_20230820_134738.png](https://github.com/jameskokoska/Allowance/assets/50821962/990ddcc1-dea1-4402-ab02-aa6ab8c1af09)

**Comment by DAJ8112** [comment]
These are the pop ups from my notification bar.

![light_notification (1)](https://github.com/jameskokoska/Allowance/assets/73093934/a1aa98e2-5c32-4eb0-bf62-ebbf34409b27) ![dark_notification (1)](https://github.com/jameskokoska/Allowance/assets/73093934/95d49e8a-3ed3-4133-9708-3ec675344a11)

When I click "Enter", i get those pop ups

**Comment by DAJ8112** [comment]
Omg did i just post another app's issue over here  .
Sorry (Newbie mistake)
