### ISSUE TITLE
"OK" label too small in pop ups

### ISSUE THREAD

**Issue by DAJ8112** [jameskokoska/Allowance#4]
#### Issue: 
OK label should be bigger in the pop up which follows when we enter a value from the notification

![dark (1)](https://github.com/jameskokoska/Allowance/assets/73093934/aed4928f-e5e0-42f1-86c3-ad32cc010e66)

**Comment by jameskokoska** [comment]
What action(s) makes this popup in the app Allowance? Form my knowledge, Allowance doesn't have a popup asking for count.

**Comment by DAJ8112** [comment]
I just post another app's issue over here  .
Really Sorry

**Comment by jameskokoska** [comment]
All good!
