### ISSUE TITLE
multple profiles for different allowances

### ISSUE THREAD

**Issue by dreamcatcher45** [jameskokoska/Allowance#5]
An option to create multiple allowances..it can be integrated to current ui like a swipable option on cash label...it would be great if its added..
### we can categories allowance to personal,work,any events,etc...I currently installed allowance app in my work profile for work based work..

**Comment by jameskokoska** [comment]
Great ideas! Unfortunately I don't see these features being planned. 

My new project, Cashew has all these features: https://github.com/jameskokoska/Cashew
Feed free to check that one out! 

Allowance is a feature limited application on purpose, for design and ease of use.
