### ISSUE TITLE
Allowance App Icon does not appear correctly on Google Pixel 7 Pro

### ISSUE THREAD

**Issue by Devetec** [jameskokoska/Allowance#6]
![Screenshot_20240304-020110](https://github.com/jameskokoska/Allowance/assets/14859846/2d5e69e2-f6d4-4f0c-b309-2c6a50c140c1)

As you can see, the icon leaves a bit of white on the right and bottom. This is not present with any other of my app icons, making it a unique issue to this app.

**Comment by jameskokoska** [comment]
Closed due to inactivity.
