### ISSUE TITLE
Edit Transaction

### ISSUE THREAD

**Issue by unoukujou** [jameskokoska/Allowance#9]
Only option is to delete (then re-create). Ability to edit would be useful when needing to change the amount on a transaction that isn't yet finalized or fix a typo in the amount or transaction name or date...

**Comment by jameskokoska** [comment]
Unfortunately I don't see these features being implemented.

My new project, Cashew has all these features: https://github.com/jameskokoska/Cashew
Feed free to check that one out!

Allowance is an intended limited application for design and ease of use. Allowance is also currently not maintained.
